# Generated by Django 4.2.7 on 2023-11-16 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('numb_home', models.CharField(max_length=64, verbose_name='Номер дома')),
                ('numb_apartament', models.CharField(max_length=20, verbose_name='Номер квартиры')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=60, verbose_name='Отчество')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Earth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqmt', models.IntegerField(verbose_name='Площадь')),
            ],
            options={
                'verbose_name': 'Земля',
                'verbose_name_plural': 'Земли',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=60, verbose_name='Отчесвто')),
                ('share', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Доля от комиссии')),
            ],
            options={
                'verbose_name': 'Риэлтор',
                'verbose_name_plural': 'Риэлтора',
            },
        ),
        migrations.CreateModel(
            name='Immovables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', models.IntegerField(verbose_name='Координаты')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='esoft.address')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(verbose_name='Этажность дома')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('numb_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='esoft.address')),
                ('sqmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqmt_home', to='esoft.earth')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(verbose_name='Этаж')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('numb_apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartament', to='esoft.address')),
                ('sqmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqmt_apartament', to='esoft.earth')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
