# Generated by Django 4.2 on 2023-12-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esoft', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='esoft.objecttype', verbose_name='Тип недвижимости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='total_area',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Площадь'),
        ),
    ]
