# Generated by Django 4.2 on 2023-12-13 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoft', '0003_object_type_alter_object_total_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='logitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='district',
            name='area',
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.AddField(
            model_name='district',
            name='area',
            field=models.TextField(default=(), verbose_name='Координаты'),
            preserve_default=False,
        ),
    ]
