# Generated by Django 4.2 on 2023-12-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esoft', '0004_remove_object_coordinates_object_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='esoft.objecttype', verbose_name='Тип объекта недвижимости'),
            preserve_default=False,
        ),
    ]
