# Generated by Django 4.2 on 2023-12-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoft', '0006_alter_object_address_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='address_house',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Номер дома'),
            preserve_default=False,
        ),
    ]
